### ISSUE TITLE
Missing RiiCpp Caused by Alternate main.py

### ISSUE THREAD

**Issue by MichaelOVertolli** [matsui528/rii#34]
When I try to run `rii.Rii(fine_quantizer=codec)` I get the following `AttributeError`.

```python
AttributeError: module 'main' has no attribute 'RiiCpp'
```
Any thoughts?

**Comment by MichaelOVertolli** [comment]
I am working in a docker container. The issue does not occur if I mount the Git cloned folder and then run `setup.py` in the container. However, if I clone the folder when building the container it fails with the same error, regardless to whether I run `setup.py` manually or not.

**Comment by MichaelOVertolli** [comment]
I figured it out: there was another `main.py` in my immediate folder structure. Your path structure should be a bit less generic and a bit more contained.

**Comment by matsui528** [comment]
I followed the folder structure proposed in in the official pybind11 example  https://github.com/pybind/python_example   Feel free to submit a PR if you can improve the structure :)
