### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by matsui528** [matsui528/rii#4]
It would be great if someone could make a logo for this repo :)

**Comment by richardbmx** [comment]
@matsui528  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by matsui528** [comment]
Hi @richardbmx,
That's great! Could you show me some examples?

**Comment by richardbmx** [comment]
@matsui528  If only I need you to explain what the project is about and what are the main functions, and the name to make a logo that represents the application

**Comment by matsui528** [comment]
This project is about a search for feature vectors (e.g., an algorithm inside an image search engine). The main function is fast and memory-efficient search. The name of the project is "Rii" :+1:

**Comment by richardbmx** [comment]
@matsui528 perfect start to work on it

**Comment by richardbmx** [comment]
@matsui528 I present my proposal, the logo is based on a magnifying glass with a lateral design that together form the letter R to give identity of search to the application, then two versions of a logo in vertical and horizontal direction with the name of the application

If you want something to change or have an idea in mind do not hesitate to say it to make it

![logo97](https://user-images.githubusercontent.com/35604837/44164362-d345be00-a093-11e8-8985-fdc5cfe6d41e.png)

**Comment by matsui528** [comment]
Hi @richardbmx,
Awesome! I like all of them and would gladly use them. Really appreciate!

**Comment by richardbmx** [comment]
@matsui528  perfect I will create a google folder with all the necessary files to use it

**Comment by richardbmx** [comment]
Here is the google folder with all the files, if you want some kind of specific file, do not hesitate to ask for it

All File
[Google Drive](https://drive.google.com/open?id=1Qdyxnh5TPpBvXxA67o5cmZKEAX4Q4dtA)

**Comment by matsui528** [comment]
@richardbmx Thank you again for you great work! Now the logo is on the top of the documentation https://rii.readthedocs.io/en/latest/ and README https://github.com/matsui528/rii with your credit :+1:

**Comment by richardbmx** [comment]
@matsui528  Perfect I am very happy that you liked my work, thank you very much for the credits
