### ISSUE TITLE
native windows support

### ISSUE THREAD

**Issue by matsui528** [matsui528/rii#40]
Need to include some headers for SIMD codes? PRs are welcome.

log: https://github.com/matsui528/rii/runs/3014401725?check_suite_focus=true

related: #39

**Comment by ashleyabraham** [comment]
With my best knowledge and ability I've attempted to make it work in Windows and here's the build run summary
https://github.com/ashleyabraham/rii/actions/runs/1082574399

**Comment by matsui528** [comment]
Thank you! Let me take a look.

**Comment by matsui528** [comment]
#42
