### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ashleyabraham** [matsui528/rii#41]
Under the  `Data addition and reconfiguration` section in Readme.md 

```
# Add new vectors
X2 = np.random.random((1000, D)).astype(np.float32)
e.add(vecs=X2)  # Now N is 11000
e.query(q=q)  # Ok. (0.12 msec / query)

# However, if you add quite a lot of vectors, the search might become slower
# because the data structure has been optimized for the initial item size (N=10000)
X3 = np.random.random((1000000, D)).astype(np.float32) 
e.add(vecs=X3)  # A lot. Now N is 1011000
e.query(q=q)  # Slower (0.96 msec/query)
```

The e.query triggers an AssertionError before calling reconfigure or add_configure

```assert lib/python3.7/site-packages/rii/rii.py in query(self, q, topk, L, target_ids, sort_target_ids, method)
    275         """
    276         assert 0 < self.N   # Make sure there are codes to be searched
--> 277         assert 0 < self.nlist   # Make sure posting lists are available
    278         assert method in ["auto", "linear", "ivf"]
    279 

AssertionError: 
```

Should this be updated to use add_configure instead of add before the query call?

**Comment by matsui528** [comment]
Seems weird. I added this test and it seems working for windows.
https://github.com/matsui528/rii/pull/43/files#diff-ebe97cfcee8f247647fe14196989469673fc3c4eb17050580719244b127c5943R56

Could you let me know the minimum example to reproduce the error?

**Comment by ashleyabraham** [comment]
I ran the same script today and I couldn't reproduce the error. Apologize for the false alarm
