### ISSUE TITLE
Clearification this technique uses approximate L2 norm or Euclidian distance to calcualate the distance?

### ISSUE THREAD

**Issue by ArEnSc** [matsui528/rii#47]
Hey does this use L2 norm or cosine simuluarity to figure out the distance?

**Comment by matsui528** [comment]
The squared L2 distance. See Eq. 2 https://dl.acm.org/ft_gateway.cfm?id=3240630

**Comment by ArEnSc** [comment]
@matsui528 to get the actual distance then I square root the distance returned ?

**Comment by matsui528** [comment]
Yes, but don't forget it's an approximated distance (the algorithm is "approximated" nearest neighbor search)

**Comment by ArEnSc** [comment]
@matsui528 perfect thanks!
